# -*- coding: utf-8 -*-
"""Fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvASRMSjKUMAUGIimic4NWx3YRc5e1mR
"""

pip install -U sentence-transformers

"""# **Task 1**
For this task I used the sentence-transfomers library. This library is built using pytorch and Higging Face's Trasformers which provides a high level API to quickly load the trasformer base models that are optimized for the sentence embaddings.

# **Architecture System**
*   I used mean pooling in pooling strategy over the token embeddings from the last hidden state.  This method would find the average all token embeddings, weighted by the attention mask.  

*   I also used fixed length embeddings which transofmrs all senteces into a vector length of 384 regardless of the original token length. This is a very importatnt step in clustering algorithms.


*   The chosen library automatically applied L2 normalization whichis useful for cosine similarities. This is beneficial in the downstream.
*   Tokenization is handled internally by the Hugging Face tokenizer associated with MiniLM. It automatically pads and truncates inputs to the model’s maximum sequence length.






"""

from sentence_transformers import SentenceTransformer
import numpy as np

# Load a pre-trained sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Sample sentences
sentences = [
    "Machine learning is fascinating.",
    "Artificial intelligence is changing the world.",
    "Cats are cute.",
    "The sun is shining today."
]

# Encode the sentences into embeddings
embeddings = model.encode(sentences)

# Apply manual L2 normalization
def l2_normalize(vec):
    return vec / np.linalg.norm(vec)

normalized_embeddings = [l2_normalize(emb) for emb in embeddings]

# Print the results
for i, emb in enumerate(normalized_embeddings):
    print(f"Sentence: {sentences[i]}")
    print(f"Normalized embedding shape: {emb.shape}")
    print(f"L2 norm: {np.linalg.norm(emb):.4f}")  # Should be 1.0
    print(f"Embedding (first 5 values): {emb[:5]}")
    print()

"""# **Task 2**

In this task, I expanded the architecture to support a multi-task learning setting by introducing two supervised classification tasks A, and B. Task A is a sentence topic classification and for Task B i sued the sentiment Analysis. I used Sentiment ANalysis becasuse it is a sentence-level classification but withdifferent lable sets such as positive, nurtral, oor negative. As for the purpose of this porject, it would be easier to use to creat fake lables and intutitve to interpret.

In this task each head is implementeas as fully connectioned linear layer which maps the pooled sentence embedding to 3 class output space. each head produces its own logic during the traiing which are compared with the ground truth lables using seprated corss-entropy loss.

For loss calculation I used the sum of the tasks specific losses which allows the model to learn both task at the same time instead of working on them individually. This approac shares the same sentece ecoder that enables the model to generalize shared features across tasks while still maintaining task specific decisions. This architecture efficiently supports multi-task learning without requiring multiple separate models.


Comparing with task 1 which the resulting embeddings were not directly used for any downstream supervised task; rather, they served as general-purpose sentence representations for potential use in clustering, similarity, or other unsupervised applications. No classification heads or loss functions were applied in Task 1, and the model was not trained or fine-tuned. It was purely used in inference mode.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from transformers import AutoModel, AutoTokenizer

class MultiTaskSentenceTransformer(nn.Module):
    def __init__(self, model_name='sentence-transformers/all-MiniLM-L6-v2',
                 num_classes_taskA=3, num_classes_taskB=3):
        super(MultiTaskSentenceTransformer, self).__init__()

        # Shared transformer backbone
        self.encoder = AutoModel.from_pretrained(model_name)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)

        hidden_size = self.encoder.config.hidden_size  # e.g., 384

        # Task A: Sentence classification head
        self.classifier_taskA = nn.Linear(hidden_size, num_classes_taskA)

        # Task B: Sentiment analysis head
        self.classifier_taskB = nn.Linear(hidden_size, num_classes_taskB)

    def forward(self, sentences, task='A'):
        # Tokenize input
        tokens = self.tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')
        outputs = self.encoder(**tokens)

        # Mean pooling (manual)
        token_embeddings = outputs.last_hidden_state
        attention_mask = tokens['attention_mask'].unsqueeze(-1)
        pooled_output = (token_embeddings * attention_mask).sum(dim=1) / attention_mask.sum(dim=1)

        if task == 'A':
            return self.classifier_taskA(pooled_output)
        elif task == 'B':
            return self.classifier_taskB(pooled_output)
        else:
            raise ValueError("Invalid task. Choose 'A' or 'B'.")
model = MultiTaskSentenceTransformer()

# Optimizer and losses
optimizer = optim.Adam(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

# Sample input
sentences = ["Cats are cute", "The cloud server crashed", "It's sunny today"]

# 🔹 Synthetic labels (fake ground truth)
labels_A = torch.tensor([1, 0, 2])  # Task A: category class (e.g., 0=Tech, 1=Animal, 2=Weather)
labels_B = torch.tensor([2, 0, 1])  # Task B: sentiment class (e.g., 0=Negative, 1=Neutral, 2=Positive)

# Training step
model.train()
optimizer.zero_grad()

# Forward passes
logits_A = model(sentences, task='A')
logits_B = model(sentences, task='B')

# Losses
loss_A = criterion(logits_A, labels_A)
loss_B = criterion(logits_B, labels_B)

# Total loss (equal weights)
total_loss = loss_A + loss_B

# Backpropagation
total_loss.backward()
optimizer.step()

# Log results
print(f"Loss Task A: {loss_A.item():.4f}")
print(f"Loss Task B: {loss_B.item():.4f}")
print(f"Total Loss: {total_loss.item():.4f}")

"""# **Task 3**

**Part A**
1. If the entire network should be frozen:
*   **Pors:** Freezing the entier network turns the model into a static feature extractor. This means no wrights are updated during the training. This can be very useful when you are only embedding for downstream use and not classification. When you have very limited labled data and you want to avoid overffiting freezing network can help a lot. The last scnario that freezing network can be useful when we want fast inderence without retrainig the whole model again.

*   **Cons:** In this model there is no trainig happen. The model won't adapt to the new tasks or datasets erformances which can act poorly on classification tasks like Task 2.



2.   If only the transformer backbone should be frozen.
*   **Pors:** This method is very common strategy in trasfer learning. This method retains the powerful sentence representation learned by the transformer and only train the task spesific heads.
*   This method can help with


 > **a.** reducing the training time and memory usage.


 > **b.** Prevent overfitting on small dataset.


>  **c.** Ensure the backone retains general lingustic knowledge


*   **Cons:** With this method, the model won't be able to adapt the core representation to domain spesific data. If the new dataset is significanlty different from what the trasormer was trained the whole model's performance will suffer.  


3. If only one of the task-specific heads (either for Task A or Task B) should be frozen.

*   **Pors:** With this method of the tasks has already been well trainied, and you want to preserve learned knowledge in one task while updating the other one.
*   **Cons:** This method canm casue task interference during shared encoding updates. The forzen head won't adapt if the encoder changes due to the training from the other task.



**Part B**

1. The choice of a pre-trained model.


*   I would select a model with a general purpose such as all-Mini_l6-v2 since the concept of the model is not defind completely. This model would help with most of the tasks and performs well.
*   For domain specific tasks, I would go with more specialized models like BERT subsutized such as SciBERT or LegalBERT.

2. The layers you would freeze/unfreeze.

*   Freezing
> **a.** Freeze the transfomers to the backbone or the pre-trained encoder

>> **b.** This would help to train only the task specific heads such as sentiment analysis

*   Unfreezing


>> **a.** Unfreeze the transoferm laters after the inital training

>>  **b.** Fine tune the entiner model so it can adap with deeper tasks


3. The rationale behind these choices.


*   This approach prevents the forgetting issue of the pre trained knowledge in the early tages of the training.
*   It would also enables the classification heads to first learn task specific patterns independently.


*   Gradual unfreezing would allow the model to refine the internal represenations for the new tasks
*   Using discriminative learning rates would ensure a controlled fine tuning. Discriminative learning can be LR for the backbone or higher LR for the heads.

# **Task 4**
"""

import torch
import torch.nn as nn
import torch.optim as optim
from transformers import AutoModel, AutoTokenizer
from sklearn.metrics import accuracy_score, f1_score

# ---------------------------
# 1. Multi-Task Model
# ---------------------------
class MultiTaskSentenceTransformer(nn.Module):
    def __init__(self, model_name='sentence-transformers/all-MiniLM-L6-v2', num_classes_taskA=3, num_classes_taskB=3):
        super(MultiTaskSentenceTransformer, self).__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        hidden_size = self.encoder.config.hidden_size
        self.classifier_taskA = nn.Linear(hidden_size, num_classes_taskA)
        self.classifier_taskB = nn.Linear(hidden_size, num_classes_taskB)

    def forward(self, sentences, task='A'):
        tokens = self.tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')
        outputs = self.encoder(**tokens)
        token_embeddings = outputs.last_hidden_state
        attention_mask = tokens['attention_mask'].unsqueeze(-1)
        pooled_output = (token_embeddings * attention_mask).sum(dim=1) / attention_mask.sum(dim=1)

        if task == 'A':
            return self.classifier_taskA(pooled_output)
        elif task == 'B':
            return self.classifier_taskB(pooled_output)
        else:
            raise ValueError("Choose task='A' or 'B'")

# ---------------------------
# 2. Hypothetical Data
# ---------------------------
sentences = ["The cloud crashed", "Cats are cute", "Sunny day in NYC"]
labels_A = torch.tensor([0, 1, 2])  # Topic: Tech, Animal, Weather
labels_B = torch.tensor([0, 2, 1])  # Sentiment: Negative, Positive, Neutral

# ---------------------------
# 3. Training Setup
# ---------------------------
model = MultiTaskSentenceTransformer()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=2e-5)

# ---------------------------
# 4. Multi-Epoch Training Loop
# ---------------------------
num_epochs = 5
model.train()

for epoch in range(num_epochs):
    optimizer.zero_grad()

    # ---- Task A
    logits_A = model(sentences, task='A')
    loss_A = criterion(logits_A, labels_A)
    preds_A = torch.argmax(logits_A, dim=1)
    acc_A = accuracy_score(labels_A.numpy(), preds_A.numpy())
    f1_A = f1_score(labels_A.numpy(), preds_A.numpy(), average='macro')

    # ---- Task B
    logits_B = model(sentences, task='B')
    loss_B = criterion(logits_B, labels_B)
    preds_B = torch.argmax(logits_B, dim=1)
    acc_B = accuracy_score(labels_B.numpy(), preds_B.numpy())
    f1_B = f1_score(labels_B.numpy(), preds_B.numpy(), average='macro')

    # ---- Total Loss
    total_loss = loss_A + loss_B
    total_loss.backward()
    optimizer.step()

    # ---- Logging
    print(f"Epoch {epoch+1}/{num_epochs}")
    print(f"  Task A - Loss: {loss_A.item():.4f}, Accuracy: {acc_A:.2f}, F1 Score: {f1_A:.2f}")
    print(f"  Task B - Loss: {loss_B.item():.4f}, Accuracy: {acc_B:.2f}, F1 Score: {f1_B:.2f}")
    print(f"  Total Loss: {total_loss.item():.4f}")
    print("-" * 50)

"""# **Task 3 and 4 documentation**
In expanding the model to support multi-task learning, we introduced two supervised tasks—sentence topic classification and sentiment analysis—built on top of a shared transformer encoder. For training strategy (Task 3), we carefully considered different freezing scenarios and adopted a phased fine-tuning approach: we initially froze the transformer backbone to allow the task-specific heads to learn independently, then gradually unfroze the backbone to fine-tune the entire model. This ensured we retained the general language knowledge from the pre-trained model while still allowing adaptation to new tasks.

We used a pre-trained model (all-MiniLM-L6-v2) to leverage strong sentence embeddings and accelerate learning. The model was trained using separate cross-entropy losses for each task, which were combined and backpropagated through the shared encoder. We tracked both accuracy and F1 score to better reflect task performance—especially important in low-resource or imbalanced scenarios. Over multiple epochs, the model showed clear improvement in both tasks, demonstrating the effectiveness of shared representation learning in a multi-task setting. These results validate our design choices and show how transfer learning can be strategically applied to maximize both efficiency and performance.
"""

